const LAB_VERSION='0.14.28';
const input=document.getElementById('input'),btn=document.getElementById('analyzeBtn'),statusEl=document.getElementById('status'),chatLog=document.getElementById('chatLog'),agendaCol=document.getElementById('agendaCol'),agendaHeadTabs=document.getElementById('agendaHeadTabs'),agendaSection=document.querySelector('section.col.agenda'),attentionCol=document.getElementById('attentionCol'),regieCol=document.getElementById('regieCol'),endPromptHost=document.getElementById('endPromptHost'),clockHour=document.getElementById('clockHour'),clockMinute=document.getElementById('clockMinute'),clockWeekday=document.getElementById('clockWeekday'),clockDate=document.getElementById('clockDate'),clockYear=document.getElementById('clockYear'),agendaPrevBtn=document.getElementById('agendaPrevBtn'),agendaNextBtn=document.getElementById('agendaNextBtn');
const STORAGE_KEY='clara_core_lab_state_v1',SESSION_STARTUP_KEY='clara_core_lab_auto_startup_done_v1',LAB_TEST_STORAGE_KEYS=[STORAGE_KEY,'clara_last_greeting_ix'];
const STARTUP_INTERNAL_PROMPT='Maak een rustige conceptplanning voor vandaag op basis van Projectbrain. Kies maximaal één eerstvolgende logische actie per actief project. Zet uitvoerbare acties als potloodblokken in de agenda. Geef hooguit één noodzakelijke vraag, een korte route vooruit en concrete open eindjes. Maak geen Projectbrain-dump, verzin geen harde afspraken, plan geen overlap, en zet wat niet eerlijk past apart als needs_time.';
const STARTUP_DONE_MSG='Ik heb alvast een rustige conceptdag klaargezet vanuit Projectbrain. Alles staat als potloodvoorstel.';
let labState={agenda:[],attention:[],tasks:[],open_threads:[],day_regie:{items_to_check:[],rollover_candidates:[],review_prompt:'',suggested_time:null,now_first_move:''},updated_at:null},activeAgendaTab='day',activeAgendaDate=null,currentController=null,isAnalyzing=false,dragState=null,thinkingId=0,startupAnalysisScheduled=false,activeAgendaEndPromptItemId=null;
function loadLabStateFromStorage(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;const o=JSON.parse(raw);if(!o||typeof o!=='object')return;labState.agenda=Array.isArray(o.agenda)?o.agenda:[];labState.attention=Array.isArray(o.attention)?o.attention:[];labState.tasks=Array.isArray(o.tasks)?o.tasks:[];labState.open_threads=Array.isArray(o.open_threads)?o.open_threads:[];const dr=o.day_regie||{};labState.day_regie={items_to_check:dr.items_to_check||[],rollover_candidates:dr.rollover_candidates||[],review_prompt:dr.review_prompt||'',suggested_time:dr.suggested_time??null,now_first_move:dr.now_first_move||''};labState.updated_at=o.updated_at||null}catch(_){}}
function saveLabStateToStorage(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({agenda:labState.agenda,attention:labState.attention,tasks:labState.tasks,open_threads:labState.open_threads,day_regie:labState.day_regie,updated_at:labState.updated_at}))}catch(_){}}
function clearStartupDoneIfEmpty(){if(dayRegieIsEmpty(labState)){try{sessionStorage.removeItem(SESSION_STARTUP_KEY)}catch(_){}}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function todayIso(){let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDaysIso(iso,days){let d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dateLabel(iso){let t=todayIso();if(iso===t)return'Vandaag';if(iso===addDaysIso(t,1))return'Morgen';if(iso===addDaysIso(t,2))return'Overmorgen';let d=new Date(`${iso}T12:00:00`);return d.toLocaleDateString('nl-NL',{weekday:'short',day:'numeric',month:'short'})}
function timeToMin(t){if(!t||!/^[0-2]?\d:[0-5]\d$/.test(t))return null;let[a,b]=t.split(':').map(Number);return a*60+b}
function timeToMinutes(t){return timeToMin(t)}
function getNowMinutes(){let n=new Date();return n.getHours()*60+n.getMinutes()}
function minToTime(m){if(m>=1440)return'00:00';m=Math.max(0,m);return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function isAgendaItemDone(i){if(!i)return false;return!!i.completed_at||i.status==='done'||i.status==='completed'}
function itemAgendaDate(i){return i.date||todayIso()}
function getItemBlockEndMinutes(i){let e=timeToMin(i.end_time),s=timeToMin(i.start_time);if(e==null&&s!=null)e=s+(i.estimated_duration_minutes||30);return e!=null&&s!=null?e:null}
function isoAtLocalDateMinutes(dateIso,totalMin){let[y,mo,d]=dateIso.split('-').map(Number),dt=new Date(y,mo-1,d,0,0,0,0),H=Math.floor(totalMin/60),M=totalMin%60;dt.setHours(H,M,0,0);return dt.toISOString()}
function shouldPromptAgendaEnd(item,now,activeAgendaDate){let tIso=todayIso(),id=itemAgendaDate(item);if(id!==tIso)return false;let endM=getItemBlockEndMinutes(item);if(endM==null)return false;if(classifyAllDay(item))return false;let st=String(item.status||'');if(isAgendaItemDone(item))return false;if(st==='needs_time'||st==='external_busy')return false;if(item.kind==='external_busy')return false;let sm=timeToMin(item.start_time);if(sm==null)return false;if(item._end_prompt_snoozed_until){let sn=Date.parse(item._end_prompt_snoozed_until);if(!isNaN(sn)&&now.getTime()<sn)return false}let nowFrac=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;if(nowFrac<endM||nowFrac>endM+30)return false;return true}
function findAgendaEndPromptCandidate(now){let c=labState.agenda.filter(i=>shouldPromptAgendaEnd(i,now,activeAgendaDate));if(!c.length)return null;c.sort((a,b)=>(getItemBlockEndMinutes(a)||0)-(getItemBlockEndMinutes(b)||0));return c[0]}
function clearAgendaEndPromptUI(){activeAgendaEndPromptItemId=null;if(endPromptHost)endPromptHost.innerHTML=''}
function clearLocalTestState(){LAB_TEST_STORAGE_KEYS.forEach(k=>{try{localStorage.removeItem(k)}catch(_){}});try{sessionStorage.removeItem(SESSION_STARTUP_KEY)}catch(_){}try{localStorage.removeItem('clara_core_lab_current_context')}catch(_){}stopThinkingStatusFlow();if(isAnalyzing&&currentController){try{currentController.abort()}catch(_){}}setAnalyzing(false);dragState=null;startupAnalysisScheduled=false;labState={agenda:[],attention:[],tasks:[],open_threads:[],day_regie:{items_to_check:[],rollover_candidates:[],review_prompt:'',suggested_time:null,now_first_move:''},updated_at:new Date().toISOString()};activeAgendaTab='day';activeAgendaDate=null;clearAgendaEndPromptUI();try{document.querySelectorAll('#chatLog .msg .options').forEach(n=>n.remove())}catch(_){}saveLabStateToStorage();clearStartupDoneIfEmpty();renderFromState();setStatus('Lokale teststaat gewist.');applyStartupGreeting()}
function labClearTestControls(){return'<p class="lab-test-row"><button type="button" class="lab-clear-test" data-action="clear-test-state">Wis lokale teststaat</button></p>'}
function showAgendaEndPrompt(item){if(!endPromptHost||!item)return;activeAgendaEndPromptItemId=item.id;let t=esc(String(item.title||'').trim()||'Blok');endPromptHost.innerHTML=`<div class="end-prompt-card" role="dialog" aria-labelledby="end-prompt-h"><div id="end-prompt-h" class="end-prompt-head">Blok afgelopen</div><div class="end-prompt-body">Dit blok liep net af: ${t}. Is dit afgerond?</div><div class="end-prompt-actions"><button type="button" class="end-prompt-btn primary" data-agenda-end-action="done" data-item-id="${esc(item.id)}">Voltooid</button><button type="button" class="end-prompt-btn" data-agenda-end-action="extend15" data-item-id="${esc(item.id)}">15 min erbij</button><button type="button" class="end-prompt-btn" data-agenda-end-action="rollover" data-item-id="${esc(item.id)}">Doorschuiven</button><button type="button" class="end-prompt-btn muted" data-agenda-end-action="later" data-item-id="${esc(item.id)}">Later</button></div></div>`}
function checkAgendaEndPrompts(){let now=new Date();if(activeAgendaEndPromptItemId){let cur=labState.agenda.find(i=>i.id===activeAgendaEndPromptItemId);if(cur&&shouldPromptAgendaEnd(cur,now,activeAgendaDate))return;clearAgendaEndPromptUI()}let next=findAgendaEndPromptCandidate(now);if(next)showAgendaEndPrompt(next)}
function handleAgendaEndPromptAction(itemId,action){let item=labState.agenda.find(i=>i.id===itemId);if(!item){clearAgendaEndPromptUI();return}let d=itemAgendaDate(item);if(action==='done'){item.status='done';item.completed_at=new Date().toISOString();delete item._end_prompt_snoozed_until}else if(action==='extend15'){let endM=getItemBlockEndMinutes(item);if(endM==null){clearAgendaEndPromptUI();touchState();renderFromState();return}endM=Math.min(24*60-1,endM+15);item.end_time=minToTime(endM);let sm=timeToMin(item.start_time);if(sm!=null)item.estimated_duration_minutes=Math.max(15,endM-sm);item._end_prompt_snoozed_until=isoAtLocalDateMinutes(d,endM);labState.agenda=markOverlaps(labState.agenda)}else if(action==='rollover'){let rawTitle=String(item.title||'').trim();item.status='needs_time';item.start_time=null;item.end_time=null;delete item._end_prompt_snoozed_until;let rc=labState.day_regie.rollover_candidates||[];if(rawTitle)labState.day_regie.rollover_candidates=[...rc,rawTitle];labState.attention.push({id:'at-end-'+Date.now()+'-'+((Math.random()*1e6)|0),title:('[Doorschuiven] '+rawTitle).slice(0,220),kind:'check',done:false,project:item.project||null})}else if(action==='later'){item._end_prompt_snoozed_until=new Date(Date.now()+15*60*1000).toISOString()}activeAgendaEndPromptItemId=null;if(endPromptHost)endPromptHost.innerHTML='';touchState();renderFromState()}
function round15(m){return Math.round(m/15)*15}
function setStatus(t){if(statusEl)statusEl.textContent=t||''}
function touchState(){labState.updated_at=new Date().toISOString();saveLabStateToStorage();clearStartupDoneIfEmpty();setStatus('Lab State bijgewerkt · gaat mee naar Clara')}
function resizeInput(){input.style.height='32px';input.style.height=Math.min(input.scrollHeight,190)+'px'}
function scrollBottom(){chatLog.scrollTop=chatLog.scrollHeight}
function setAnalyzing(on){isAnalyzing=on;btn.classList.toggle('stop',on);btn.textContent=on?'■':'↑'}
function addUserMessage(t){chatLog.insertAdjacentHTML('beforeend',`<div class="msg user"><div class="msg-body">${esc(t)}</div></div>`);scrollBottom()}
function addThinking(){thinkingId++;let id='thinking-'+thinkingId;chatLog.insertAdjacentHTML('beforeend',`<div class="msg assistant thinking" id="${id}"><div class="msg-body"><div class="typing-indicator" aria-hidden="true"><span class="typing-dot"></span><span class="typing-dot"></span><span class="typing-dot"></span></div><div class="thinking-status" id="${id}-status" role="status" aria-live="polite"></div></div></div>`);scrollBottom();return id}
function removeThinking(id){document.getElementById(id)?.remove()}
function setThinkingStatus(thinkingId,t){let el=document.getElementById(thinkingId+'-status');if(el)el.textContent=t==null?'':String(t)}
function clearThinkingStatus(thinkingId){setThinkingStatus(thinkingId,'')}
const THINKING_STATUS_STEPS=['Input lezen','Lokale dagstaat ophalen','Projectbrain raadplegen','Projectcontext wegen','Agenda voorstel maken','Keuzes scheiden','Route opbouwen','Overlap controleren','Resultaat bijwerken'];
let thinkingFlowTimer=null,thinkingFlowToken=0,thinkingFlowThinkingId=null,thinkingFlowStepIdx=0;
function stopThinkingStatusFlow(){thinkingFlowToken++;if(thinkingFlowTimer){clearTimeout(thinkingFlowTimer);thinkingFlowTimer=null}thinkingFlowThinkingId=null}
function startThinkingStatusFlow(thinkingId){stopThinkingStatusFlow();thinkingFlowThinkingId=thinkingId;const my=thinkingFlowToken;thinkingFlowStepIdx=0;setThinkingStatus(thinkingId,THINKING_STATUS_STEPS[0]);function tick(){if(my!==thinkingFlowToken||thinkingFlowThinkingId!==thinkingId)return;const gap=700+Math.random()*500;thinkingFlowTimer=setTimeout(()=>{if(my!==thinkingFlowToken||thinkingFlowThinkingId!==thinkingId)return;if(thinkingFlowStepIdx<THINKING_STATUS_STEPS.length-1){thinkingFlowStepIdx++;setThinkingStatus(thinkingId,THINKING_STATUS_STEPS[thinkingFlowStepIdx]);tick()}else{function pulse(){if(my!==thinkingFlowToken||thinkingFlowThinkingId!==thinkingId)return;pulse.n=(pulse.n||0)+1;setThinkingStatus(thinkingId,pulse.n%2?THINKING_STATUS_STEPS[8]:THINKING_STATUS_STEPS[7]);thinkingFlowTimer=setTimeout(pulse,1100+Math.random()*400)}thinkingFlowTimer=setTimeout(pulse,gap)}},gap)}tick()}
function updateDate(){let n=new Date(),shown=activeAgendaDate?new Date(`${activeAgendaDate}T12:00:00`):n;clockHour.textContent=String(n.getHours()).padStart(2,'0');clockMinute.textContent=String(n.getMinutes()).padStart(2,'0');clockWeekday.textContent=shown.toLocaleDateString('en-US',{weekday:'long'});clockDate.textContent=shown.toLocaleDateString('en-GB',{day:'numeric',month:'long'}).toUpperCase();clockYear.textContent=shown.getFullYear()}
function markOverlaps(items){let out=items.map(i=>({...i,_frontend_conflict:false}));let timed=out.map((i,idx)=>({i,idx,s:timeToMin(i.start_time),e:timeToMin(i.end_time)})).filter(x=>x.s!=null&&!isAgendaItemDone(x.i));timed.forEach(x=>{if(x.e==null)x.e=x.s+(x.i.estimated_duration_minutes||30)});for(let a=0;a<timed.length;a++)for(let b=a+1;b<timed.length;b++)if(timed[a].i.date===timed[b].i.date&&timed[a].s<timed[b].e&&timed[b].s<timed[a].e){out[timed[a].idx]._frontend_conflict=true;out[timed[b].idx]._frontend_conflict=true}out.forEach(i=>{if(i.status==='conflict'&&!i._frontend_conflict)i.status='pencil'});return out}
const NEUTRAL_START=['Begin klein: één helder blok is genoeg om de dag op gang te krijgen.','Kijk eerst wat vastligt, daarna pas wat erbij kan.','Maak ruimte voor het belangrijkste, niet voor het luidste.','Vandaag hoeft niet vol; het moet kloppen.','Eerst overzicht, daarna tempo.'];
const ATT_KINDS=new Set(['risico','keuze','check','wacht','past_niet','project']);
const ATT_LABEL_NL={risico:'Risico',keuze:'Keuze',check:'Check',wacht:'Wacht',past_niet:'Past niet',project:'Project'};
function simpleHash(str){let h=0;for(let i=0;i<str.length;i++)h=Math.imul(31,h)+str.charCodeAt(i)|0;return Math.abs(h)}
function rememberLastStartupGreeting(ix){try{localStorage.setItem('clara_last_greeting_ix',String(ix))}catch(_){}}
function formatAttentionLabel(kind){return ATT_LABEL_NL[kind]||'Check'}
function getAttentionType(item){return item&&ATT_KINDS.has(item.kind)?item.kind:'check'}
function coerceAttentionItem(raw,i){if(!raw)return null;if(typeof raw==='string'){const s=raw.trim();if(!s)return null;return{id:'at-'+Date.now()+'-'+i,title:s.slice(0,220),kind:'check',done:false}}const title=String(raw.title||raw.text||'').trim();if(!title)return null;const k=raw.kind&&ATT_KINDS.has(raw.kind)?raw.kind:'check';return{id:raw.id||'at-'+Date.now()+'-'+i,title:title.slice(0,220),kind:k,done:!!raw.done,project:raw.project||null}}
function normalizeAttentionItems(items){const arr=Array.isArray(items)?items:[];const out=[],seen=new Set();for(let i=0;i<arr.length;i++){const it=coerceAttentionItem(arr[i],i);if(!it)continue;const k=it.title.toLowerCase();if(seen.has(k))continue;seen.add(k);out.push(it)}return out}
function isGenericAttentionMeta(title){const t=String(title||'').toLowerCase().trim();if(t.length<10)return false;const bans=[/projectbrain.*(aandacht|bewaren|opnemen)/,/bewaar.*(keuzes|risico).*projectbrain/,/geen\s+overlap/,/plan\s+geen\s+overlap/,/voorkom.*overlap/,/verkorten\s+van\s+taken/,/taken\s+niet\s+verkorten/,/geen\s+projectbrain[-\s]?dump/,/geen\s+dump/,/maak\s+geen\s+dump/,/projectbrain\s+als\s+context/,/gebruik\s+projectbrain\s+als/,/^twijfel:\s*projectbrain\s+is\s+beperkt/,/potloodblokken\s+zijn\s+geen\s+harde/,/controleer\s+per\s+project\s+of\s+de\s+duur/i,/schuif\s+desnoods\s+in\s+de\s+ui/i,/bewaar\s+.*\s+in\s+de\s+aandacht/i];return bans.some(re=>re.test(t))}
function attentionTitleMatchesAgenda(title,agenda){const s=String(title||'').trim().toLowerCase();if(!s)return true;return(agenda||[]).some(i=>{const tt=String(i.title||'').trim().toLowerCase();return tt&&tt===s})}
function enrichAttentionFromLabState(agenda,tasks,existing){const out=[];const have=new Set((existing||[]).map(i=>i.title.toLowerCase()));function add(title,kind,project){const k=title.toLowerCase();if(!title||have.has(k))return;have.add(k);out.push({id:'at-h-'+Date.now()+'-'+out.length,title,kind,done:false,project})}const blob=[...(agenda||[]),...(tasks||[])].map(i=>`${i.title||''} ${i.project||''}`).join(' ').toLowerCase();if(/mobiel|responsive|marlon|push|vercel|core\s*lab|clara[-\s]?4[-\s]?core/i.test(blob))add('Mobiel goed krijgen vóór push of Marlon-review','check','clara-core-lab');if(/begeister|grens|rollen|gezamenlijk|autonoom|lalampe/.test(blob))add('Begeister-grens: gezamenlijk versus LaLampe versus autonoom bepalen','keuze','begeister');if(/\bafk\b|ecolog|maatschappij|aanvraag|landjuweel|amarte/.test(blob))add('AFK-aanvraag ecologisch houden, niet onbedoeld maatschappijkritisch','risico','afk-landjuweel-amarte');if(/lalampe|lampe|materiaal|lamp|workshop/.test(blob))add('LaLampe: materiaal, lampenkappen of workshopflow nog nalopen','check','lalampe');return out}
function pickContextLineForStartup(ls){const agenda=markOverlaps([...(ls.agenda||[])]);if(agenda.some(i=>i._frontend_conflict))return'Er staat overlap in je agenda; los één blok eerst op.';if(agenda.some(i=>i.status==='needs_time'))return'Er staat werk zonder vaste plek; kies waar het vandaag past.';const att=normalizeAttentionItems(ls.attention||[]);const open=att.filter(i=>!i.done);if(open.length)return`Er staan ${open.length} aandachtspunten open; pak het belangrijkste eerst.`;const tk=(ls.tasks||[]).filter(t=>!t.done);if(tk.length)return`${tk.length} taken wachten; begin met de kleinste afronding.`;if(agenda.some(i=>i.status==='pencil'))return'Er staan potloodblokken klaar om te bevestigen of te schuiven.';return null}
function pickStartupGreeting(ls){const ctx=pickContextLineForStartup(ls);const pool=ctx?[ctx,...NEUTRAL_START]:NEUTRAL_START.slice();const t=new Date();const salt=`${t.getFullYear()}-${t.getMonth()+1}-${t.getDate()}-${t.getHours()}-${simpleHash(JSON.stringify({a:ls.agenda,at:ls.attention,tk:ls.tasks,dr:ls.day_regie}))}`;let h=simpleHash(salt)%pool.length;let last=-1;try{last=parseInt(localStorage.getItem('clara_last_greeting_ix')||'-1',10)}catch(_){}if(h===last)h=(h+1)%pool.length;rememberLastStartupGreeting(h);return pool[h]}
function applyStartupGreeting(){const wrap=document.querySelector('#chatLog .msg.assistant:not(.thinking)');if(!wrap)return;const text=pickStartupGreeting(labState);wrap.innerHTML=`<div class="msg-body">${esc(text)}</div>`}
function ellip(s,max){s=String(s||'').trim();return s.length<=max?s:s.slice(0,max-1)+'…'}
function pickNowStep(ls){const dr=ls.day_regie||{};const nfm=String(dr.now_first_move||'').trim();if(nfm.length>16){const t=todayIso();const titles=(ls.agenda||[]).filter(i=>(i.date||t)===t).map(i=>String(i.title||'').trim().toLowerCase());const nml=nfm.toLowerCase();if(!titles.some(tt=>tt&&nml===tt))return ellip(nfm,160)}const agenda=markOverlaps([...(ls.agenda||[])]);const today=todayIso();const att=normalizeAttentionItems(ls.attention||[]);const risk=att.find(i=>!i.done&&(i.kind==='risico'||i.kind==='past_niet'));if(risk)return ellip(`${formatAttentionLabel(risk.kind)} — ${risk.title}`,72);const w=att.find(i=>!i.done&&i.kind==='wacht');if(w)return ellip(`${formatAttentionLabel(w.kind)} — ${w.title}`,72);const timed=agenda.filter(i=>(i.date||today)===today&&i.start_time&&timeToMin(i.start_time)!=null&&!classifyAllDay(i)&&i.status!=='needs_time'&&!isAgendaItemDone(i)).sort((a,b)=>(timeToMin(a.start_time)-timeToMin(b.start_time)));if(timed.length){const ti=timed[0],title=String(ti.title||'').trim(),blob=`${title} ${ti.project||''}`.toLowerCase();const why=/core|lab|mobiel|marlon|push|vercel/.test(blob)?'dat bepaalt of Marlon straks redelijk mee kan kijken.':'dat zet volgorde voor de rest van de dag.';return ellip(`Start met ${title}; ${why}`,78)}const nt=agenda.find(i=>(i.date||today)===today&&i.status==='needs_time');if(nt)return ellip(`Past niet — ${nt.title}`,72);const task=(ls.tasks||[]).find(x=>!x.done);if(task)return ellip(`Pak eerst "${task.title}" vast in de dag voordat je opschaling doet.`,72);const o=att.find(i=>!i.done);if(o)return ellip(`${formatAttentionLabel(o.kind)} — ${o.title}`,72);return'Kort orienteren: wat is het belangrijkste vaste punt vandaag?'}
function agendaTitlesToday(ls){const t=todayIso();return(ls.agenda||[]).filter(i=>(i.date||t)===t).map(i=>String(i.title||'').trim().toLowerCase()).filter(Boolean)}
function lineLooksLikeAgendaTitle(line,titles){const n=String(line||'').trim().toLowerCase();if(!n)return true;return titles.some(tt=>tt&&(tt===n||(Math.min(tt.length,n.length)>=10&&(tt.includes(n)||n.includes(tt)))))}
function pickLaterChecks(ls){const titles=agendaTitlesToday(ls);let raw=[];for(const t of ls.day_regie?.items_to_check||[]){const s=String(t||'').trim();if(s&&!lineLooksLikeAgendaTitle(s,titles)&&!isGenericAttentionMeta(s))raw.push(s)}for(const t of ls.day_regie?.rollover_candidates||[]){if(raw.length>=2)break;const s=String(t||'').trim();if(s&&!lineLooksLikeAgendaTitle(s,titles)&&!isGenericAttentionMeta(s))raw.push(`Door: ${s}`)}if(!raw.length&&titles.some(tt=>/mobiel|core|lab|marlon|push|vercel/.test(tt))){raw.push('Controleer lokaal en mobiel vóór je pusht of Marlon uitnodigt.');raw.push('Zet pas daarna de review-link klaar als de staat klopt.')}else if(raw.length<2&&titles.length){raw.push('Controleer of wat op de agenda staat nog strookt met je Projectbrain-keuzes.')}return raw.slice(0,2).map(s=>ellip(s,76))}
function pickEndOfDayPrompt(ls){const r=String(ls.day_regie?.review_prompt||'').trim();if(!r||r.length<16||/^wil je de potlood/i.test(r)||/^kloppen de/i.test(r))return'Wat is af genoeg om online te tonen, en wat schuift door?';return ellip(r,84)}
function dayRegieIsEmpty(ls){const d=ls.day_regie||{};const bare=!(d.items_to_check||[]).length&&!(d.rollover_candidates||[]).length&&!String(d.review_prompt||'').trim()&&!d.suggested_time&&!String(d.now_first_move||'').trim();return bare&&!(ls.agenda||[]).length&&!(ls.attention||[]).length&&!(ls.tasks||[]).length}
function guidanceText(v,max=120){return ellip(String(v||'').replace(/\s+/g,' ').trim(),max)}
function suggestionChip(label,action,id,text){return`<button type="button" class="guide-chip" data-suggestion-action="${esc(action)}" data-id="${esc(id)}" data-title="${esc(text||'')}">${esc(label)}</button>`}
function uniqueGuidanceLines(lines,max){const out=[],seen=new Set();for(const raw of lines){const s=guidanceText(raw,150);const k=s.toLowerCase();if(!s||s.length<5||seen.has(k)||isGenericAttentionMeta(s))continue;seen.add(k);out.push(s);if(out.length>=max)break}return out}
function isUrgentOpenEnd(text,source){const s=String(text||'').toLowerCase();return source==='question'||/\\?|conflict|overlap|deadline|vandaag|straks|marlon|demo|risico|blokker|blocking|moet|keuze|onzeker|niet duidelijk|exacte tijd/.test(s)}
function deriveAgendaSuggestions(ls){const lines=[];for(const i of ls.agenda||[]){if(isAgendaItemDone(i)||i.status==='needs_time')continue;const t=String(i.title||'').trim();if(t&&!/dagbrede|geen/i.test(t))lines.push({id:i.id||'ag-'+simpleHash(t),source:'agenda',text:t,project:i.project||null})}for(const i of ls.tasks||[]){if(!i.done&&i.title)lines.push({id:i.id||'ta-'+simpleHash(i.title),source:'task',text:i.title,project:i.project||null})}const now=String(ls.day_regie?.now_first_move||'').trim();if(now)lines.unshift({id:'now-'+simpleHash(now),source:'day_regie',text:now,project:null});if(!lines.length){const blob=[...(ls.attention||[]),...(ls.open_threads||[])].map(i=>`${i.title||''} ${i.question||''} ${i.project||''}`).join(' ').toLowerCase();if(/marlon|demo|core\\s*lab|clara/.test(blob))lines.push({id:'demo-check',source:'suggestion',text:'Demo-klaarheidscheck doen',project:'clara-core-lab'});else lines.push({id:'first-step',source:'suggestion',text:'Eén concrete eerstvolgende stap kiezen',project:null})}return uniqueGuidanceLines(lines.map(x=>x.text),4).map((text,idx)=>{const src=lines.find(x=>guidanceText(x.text,150)===text)||{};return{id:src.id||'sg-'+idx,source:src.source||'suggestion',project:src.project||null,text}})}
function deriveOpenEnds(ls){const lines=[];for(const i of ls.open_threads||[]){if(i&&i.status!=='closed')lines.push({id:i.id,source:'thread',text:i.question||i.title||i.context,project:i.project||null})}for(const q of ls.questions||[])lines.push({id:'q-'+simpleHash(q),source:'question',text:q,project:null});for(const i of normalizeAttentionItems(ls.attention||[])){if(!i.done)lines.push({id:i.id,source:'attention',text:i.title,project:i.project||null})}for(const i of ls.agenda||[]){if(i.status==='needs_time')lines.push({id:i.id,source:'agenda',text:`${i.title||'Werk'} heeft nog geen plek.`,project:i.project||null});if(i._frontend_conflict)lines.push({id:i.id,source:'agenda',text:`Overlap rond ${i.title||'agenda-item'}.`,project:i.project||null})}for(const t of ls.day_regie?.items_to_check||[])lines.push({id:'chk-'+simpleHash(t),source:'check',text:t,project:null});for(const t of ls.day_regie?.rollover_candidates||[])lines.push({id:'roll-'+simpleHash(t),source:'rollover',text:`Geparkeerd: ${t}`,project:null});const uniq=uniqueGuidanceLines(lines.map(x=>x.text),8).map((text,idx)=>{const src=lines.find(x=>guidanceText(x.text,150)===text)||{};return{id:src.id||'oe-'+idx,source:src.source||'note',project:src.project||null,text,urgent:isUrgentOpenEnd(text,src.source)}});return[...uniq.filter(i=>i.urgent),...uniq.filter(i=>!i.urgent)].slice(0,5)}
function renderAgendaSuggestionsPanel(ls){const suggestions=deriveAgendaSuggestions(ls);if(!suggestions.length)return'<div class="card guide-card guide-route"><p class="empty">Geen agenda-suggesties.</p></div>';const rows=suggestions.map(i=>`<div class="item guide-suggestion-item" data-id="${esc(i.id)}"><div class="guide-suggestion-text">${esc(i.text)}${i.project?`<div class="sub">${esc(i.project)}</div>`:''}<div class="guide-chips guide-row-chips">${suggestionChip('Doe nu','now',i.id,i.text)}${suggestionChip('Plan','plan',i.id,i.text)}${suggestionChip('Parkeer','park',i.id,i.text)}</div></div></div>`).join('');return`<div class="card guide-card guide-route">${rows}</div>`}
function renderOpenEndsPanel(ls){const open=deriveOpenEnds(ls);if(!open.length)return'<div class="card guide-card guide-open"><p class="empty">Geen open eindjes.</p>'+labClearTestControls()+'</div>';const rows=open.map(i=>`<div class="item guide-open-item ${i.urgent?'urgent':''}" data-open-source="${esc(i.source)}" data-id="${esc(i.id)}"><div class="guide-open-text">${esc(i.text)}${i.project?`<div class="sub">${esc(i.project)}</div>`:''}<div class="guide-chips guide-row-chips"><button type="button" class="guide-chip" data-open-action="hang" data-id="${esc(i.id)}" data-open-source="${esc(i.source)}">Laat staan</button><button type="button" class="guide-chip" data-open-action="close" data-id="${esc(i.id)}" data-open-source="${esc(i.source)}">Sluit</button><button type="button" class="guide-chip" data-open-action="plan" data-id="${esc(i.id)}" data-open-source="${esc(i.source)}">Plan</button></div></div></div>`).join('');return`<div class="card guide-card guide-open">${rows}`+labClearTestControls()+'</div>'}
function classifyAllDay(i){let s=timeToMin(i.start_time),e=timeToMin(i.end_time),d=i.estimated_duration_minutes||(s!=null&&e!=null?e-s:null);return s==null||i.status==='needs_time'||d>=300}
function isAgendaPencilLike(i){if(!i||i._frontend_conflict)return false;if(i.status==='confirmed')return false;if(i.status==='pencil')return true;if(i.confirmation_required===true)return true;if(String(i.source||'')==='projectbrain_startup')return true;if(String(i.kind||'')==='planned_task'&&!isAgendaItemDone(i))return true;return false}
function getProjectVisual(project){const raw=String(project||'').trim();const s=raw.toLowerCase();if(!s)return{key:'none',label:'',className:'project-none',hasProject:false};if(/\bafk\b|landjuweel|amarte|afk\s*\/\s*landjuweel|afk\s+landjuweel\s+amarte/.test(s))return{key:'afk',label:'AFK',className:'project-afk',hasProject:true};if(/lalampe|la\s*lampe/.test(s))return{key:'lalampe',label:'LALAMPE',className:'project-lalampe',hasProject:true};if(/begeister/.test(s))return{key:'begeister',label:'BEGEISTER',className:'project-begeister',hasProject:true};if(/clara-core|core\s*lab|clara\s*[-\s]?4|clara\s*lab|\bclara\b/.test(s))return{key:'clara',label:'CLARA',className:'project-clara',hasProject:true};return{key:'none',label:'',className:'project-none',hasProject:false}}
function renderAgendaLegend(){return'<div class="agenda-legend" aria-label="Projectkleuren"><span class="agenda-leg agenda-leg-clara"><i class="agenda-leg-dot" aria-hidden="true"></i>CLARA</span><span class="agenda-leg-sep">·</span><span class="agenda-leg agenda-leg-lalampe"><i class="agenda-leg-dot" aria-hidden="true"></i>LALAMPE</span><span class="agenda-leg-sep">·</span><span class="agenda-leg agenda-leg-begeister"><i class="agenda-leg-dot" aria-hidden="true"></i>BEGEISTER</span><span class="agenda-leg-sep">·</span><span class="agenda-leg agenda-leg-afk"><i class="agenda-leg-dot" aria-hidden="true"></i>AFK</span></div>'}
function syncFromAnalysis(data){let agenda=markOverlaps(data.clara_agenda||[]).map((i,idx)=>({id:'ag-'+Date.now()+'-'+idx,...i}));let dash=data.dashboard_output||{};const rawAtt=[];for(const t of agenda.filter(x=>x._frontend_conflict).map(x=>x.title))if(t)rawAtt.push({title:t,kind:'risico'});for(const x of dash.attention||[]){if(typeof x==='string'&&x.trim())rawAtt.push({title:x.trim(),kind:'check'});else if(x&&x.text)rawAtt.push({title:String(x.text).trim(),kind:ATT_KINDS.has(x.kind)?x.kind:'check'})}for(const p of data.proposed_items||[])if(p.type==='attention')rawAtt.push({title:p.title,kind:'check',project:p.project||null});const rawFiltered=rawAtt.filter(r=>r&&r.title&&!isGenericAttentionMeta(r.title)&&!attentionTitleMatchesAgenda(r.title,agenda));let attention=normalizeAttentionItems(rawFiltered.map((r,i)=>({id:'at-'+Date.now()+'-'+i+'-'+((Math.random()*1e6)|0),...r,done:false})));if(attention.length<3){const ex=enrichAttentionFromLabState(agenda,(data.proposed_items||[]).filter(i=>['task','reminder'].includes(i.type)),attention);attention=normalizeAttentionItems([...attention,...ex.map((r,i)=>({id:r.id||'at-'+Date.now()+'-x-'+i,...r}))])}if(attention.length>5)attention=attention.slice(0,5);const dr=data.day_review||{};labState={agenda,attention,tasks:(data.proposed_items||[]).filter(i=>['task','reminder'].includes(i.type)).map((i,idx)=>({id:'ta-'+Date.now()+'-'+idx,title:i.title,done:false,project:i.project||null})),open_threads:Array.isArray(data.open_threads)?data.open_threads:[],day_regie:{items_to_check:dr.items_to_check||[],rollover_candidates:dr.rollover_candidates||[],review_prompt:dr.review_prompt||'',suggested_time:dr.suggested_time??null,now_first_move:dr.now_first_move||''},updated_at:new Date().toISOString()};saveLabStateToStorage()}
function renderTimeline(items,startHour,endHour,label){let start=startHour*60,end=endHour*60,total=end-start,hours=[];for(let m=start;m<=end;m+=60)hours.push(m);let labels=hours.map(m=>`<div class="hour" style="top:${(m-start)/total*100}%">${minToTime(m)}</div><div class="tick" style="top:${(m-start)/total*100}%"></div>`).join('');let lines=hours.map(m=>`<div class="line" style="top:${(m-start)/total*100}%"></div>`).join('');let blocks=items.map(i=>{let s=timeToMin(i.start_time),e=timeToMin(i.end_time),dur=i.estimated_duration_minutes||(e!=null&&s!=null?e-s:30)||30,itemEnd=e??s+dur,visibleStart=Math.max(start,s),visibleEnd=Math.min(end,itemEnd),rawH=(visibleEnd-visibleStart)/total*100,h=Math.max(2.05,rawH-0.92),top=(visibleStart-start)/total*100+0.1,compact=(itemEnd-s)<=22||rawH<4.5,st=i._frontend_conflict?'conflict':i.status==='confirmed'?'confirmed':'pencil',stAg=st==='conflict'?'agenda-item--conflict':st==='confirmed'?'agenda-item--confirmed':'agenda-item--pencil',pv=getProjectVisual(i.project),sug=isAgendaPencilLike(i)&&st!=='conflict',t0=esc(i.start_time||''),t1=esc(i.end_time||minToTime(itemEnd)),tr=t0+'–'+t1,done=isAgendaItemDone(i),projEl=pv.hasProject?`<span class="agenda-item-project">${esc(pv.label)}</span>`:'',confirm=i.status==='pencil'?`<button type="button" class="plain" data-agenda-action="confirm" data-id="${esc(i.id)}">✓</button>`:'',meta=`<div class="agenda-item-meta">${projEl}<span class="agenda-item-time">${tr}</span><span class="agenda-item-actions">${confirm}<button type="button" class="plain" data-agenda-action="delete" data-id="${esc(i.id)}">×</button></span></div>`,sugCls=sug?' agenda-item--suggest':'',doneCls=done?' agenda-item--done':'';return `<div class="event ${st} ${stAg} ${compact?'compact':''} ${pv.className}${sugCls}${doneCls}" data-project="${esc(pv.key)}" style="top:${top}%;height:${h}%"><div class="handle top" data-resize="start" data-id="${esc(i.id)}"></div><div class="event-body agenda-item-inner"><span class="event-title agenda-item-title" contenteditable="true" data-agenda-field="title" data-id="${esc(i.id)}">${esc(i.title)}</span>${meta}</div><div class="handle bottom" data-resize="end" data-id="${esc(i.id)}"></div></div>`}).join('');return `<div class="timeline-card" data-start="${start}" data-end="${end}"><div class="section-head"><strong>${esc(label)}</strong><span>${minToTime(start)} – ${minToTime(end)}</span></div><div class="timeline"><div class="axis">${labels}</div><div class="events">${lines}${blocks}</div></div></div>`}
function renderAgenda(){if(agendaHeadTabs)agendaHeadTabs.innerHTML='';let allA=labState.agenda;if(!allA.length){agendaCol.innerHTML='<p class="empty">Geen agenda-items.</p>';updateDate();return}let dates=[...new Set(allA.map(i=>i.date).filter(Boolean))].sort();if(!activeAgendaDate)activeAgendaDate=dates[0]||todayIso();let dateItems=allA.filter(i=>(i.date||activeAgendaDate)===activeAgendaDate&&!isAgendaItemDone(i));let all=dateItems.filter(classifyAllDay),timed=dateItems.filter(i=>!classifyAllDay(i)&&timeToMin(i.start_time)!=null),day=timed.filter(i=>timeToMin(i.start_time)<1140),eve=timed.filter(i=>timeToMin(i.start_time)>=1140),shown=activeAgendaTab==='day'?day:eve,labelTab=activeAgendaTab==='day'?'Overdag':'Avond';if(agendaHeadTabs)agendaHeadTabs.innerHTML=`<button type="button" class="tab ${activeAgendaTab==='day'?'active':''}" data-agenda-tab="day">Overdag</button><button type="button" class="tab ${activeAgendaTab==='evening'?'active':''}" data-agenda-tab="evening">Avond</button>`;updateDate();agendaCol.innerHTML=`<div class="agenda-stack"><span class="pill pill-daybread">${all.length?all.map(i=>esc(i.title)).join(' · '):'Geen dagbrede blokken'}</span><div class="agenda-timeline-host">${renderTimeline(shown,activeAgendaTab==='day'?10:19,activeAgendaTab==='day'?19:24,`${dateLabel(activeAgendaDate)} · ${labelTab}`)}</div>${renderAgendaLegend()}</div>`}
function renderList(title,items,kind){return `<div class="card"><h3>${esc(title)}</h3>${items&&items.length?items.map(i=>`<div class="item"><button class="box ${i.done?'done':''}" data-list-kind="${kind}" data-list-action="toggle" data-id="${esc(i.id)}"></button><div style="flex:1"><div class="editable" contenteditable="true" data-list-kind="${kind}" data-list-field="title" data-id="${esc(i.id)}">${esc(i.title)}</div>${i.project?`<div class="sub">${esc(i.project)}</div>`:''}</div><button class="plain" data-list-kind="${kind}" data-list-action="delete" data-id="${esc(i.id)}">×</button></div>`).join(''):'<p class="empty">Geen.</p>'}</div>`}
function renderRegie(){regieCol.innerHTML=renderOpenEndsPanel(labState)}
function renderGuidance(){attentionCol.innerHTML=renderAgendaSuggestionsPanel(labState)}
function renderFromState(){labState.agenda=markOverlaps(labState.agenda);labState.attention=normalizeAttentionItems(labState.attention);labState.open_threads=Array.isArray(labState.open_threads)?labState.open_threads:[];renderAgenda();renderGuidance();renderRegie();checkAgendaEndPrompts()}
function deriveSuggestions(){let conf=labState.agenda.filter(i=>i._frontend_conflict&&!isAgendaItemDone(i)),pencils=labState.agenda.filter(i=>i.status==='pencil'&&!isAgendaItemDone(i));if(conf.length)return[{type:'conflict',text:'Er is overlap in je agenda. Zal ik een oplossing voorstellen?'}];if(pencils.length)return[{type:'confirm_all',text:'Klopt deze planning zo? Dan bevestig ik alle potloodblokken.'}];return[]}
function addAssistantMessage(text,suggestions){let opt=suggestions&&suggestions.length?`<div class="options"><div class="option-text">${esc(suggestions[0].text)}</div><div class="option-actions"><button data-proposal-action="decline">Afslaan</button><button data-proposal-action="ok" data-kind="${esc(suggestions[0].type)}">Okay</button></div></div>`:'';chatLog.insertAdjacentHTML('beforeend',`<div class="msg assistant"><div class="msg-body">${esc(text)}</div>${opt}</div>`);scrollBottom()}
function contextPayload(message){return 'Actuele lokale Clara Lab State, inclusief handmatige wijzigingen. Behandel dit als waarheid:\n'+JSON.stringify(labState,null,2)+'\n\nNieuw bericht:\n'+message}
function hasOpenThreads(ls){return(ls.open_threads||[]).some(i=>i&&i.status!=='closed')}
function hasDayRegieContent(ls){const d=ls.day_regie||{};return!!((d.items_to_check||[]).length||(d.rollover_candidates||[]).length||String(d.review_prompt||'').trim()||d.suggested_time||String(d.now_first_move||'').trim())}
function onlyOpenThreadRegie(ls){const d=ls.day_regie||{};return!d.suggested_time&&!(d.items_to_check||[]).length&&!(d.rollover_candidates||[]).length&&!String(d.review_prompt||'').trim()&&/^open gesprek:/i.test(String(d.now_first_move||'').trim())}
function startupResultMessage(ls){if((ls.agenda||[]).length)return STARTUP_DONE_MSG;if(hasOpenThreads(ls))return'Er hangen nog een paar open items. Ik kan ze met je langslopen.';return'Er staat nog niets gepland.'}
function startupFallbackMessage(){return'Ik ben gestart. Er staat nog niets gepland; stel me een vraag of vraag om een conceptdag.'}
function analysisFallbackMessage(){return'Ik kon deze analyse niet goed afronden. Probeer het nog eens, of vraag om een kleinere conceptdag.'}
function render(data){syncFromAnalysis(data);renderFromState();addAssistantMessage(String(data.summary||startupResultMessage(labState)).slice(0,520),deriveSuggestions())}
function renderStartupResult(data){syncFromAnalysis(data);renderFromState();const wrap=document.querySelector('#chatLog .msg.assistant:not(.thinking) .msg-body');if(wrap)wrap.textContent=startupResultMessage(labState);try{sessionStorage.setItem(SESSION_STARTUP_KEY,'1')}catch(_){}setStatus('Concept klaar · v'+LAB_VERSION)}
async function runAutoStartupPlanning(){if(isAnalyzing)return;if(startupAnalysisScheduled)return;startupAnalysisScheduled=true;const first=document.querySelector('#chatLog .msg.assistant:not(.thinking) .msg-body');if(first)first.textContent='Een moment — ik lees Projectbrain en kijk wat er open staat.';const thinking=addThinking();currentController=new AbortController();setAnalyzing(true);setStatus('Clara start vanuit Projectbrain…');startThinkingStatusFlow(thinking);const to=setTimeout(()=>currentController.abort(),60000);try{const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:STARTUP_INTERNAL_PROMPT,source:'projectbrain_startup',lab_state:labState}),signal:currentController.signal}),data=await res.json();if(!res.ok)throw new Error(data.message||data.error||'Startanalyse mislukt');stopThinkingStatusFlow();removeThinking(thinking);renderStartupResult(data)}catch(e){stopThinkingStatusFlow();removeThinking(thinking);renderFromState();if(first)first.textContent=startupFallbackMessage();try{sessionStorage.setItem(SESSION_STARTUP_KEY,'1')}catch(_){}setStatus('Clara is klaar voor input · v'+LAB_VERSION)}finally{stopThinkingStatusFlow();clearTimeout(to);currentController=null;setAnalyzing(false);startupAnalysisScheduled=false;scrollBottom()}}
async function analyzeText(message,showUser=true){if(isAnalyzing&&currentController){currentController.abort();return}let value=String(message||'').trim();if(!value){setStatus('Voer eerst tekst in.');return}if(showUser)addUserMessage(value);input.value='';resizeInput();currentController=new AbortController();setAnalyzing(true);setStatus('Clara analyseert met lokale Lab State...');let thinking=addThinking(),to=setTimeout(()=>currentController.abort(),60000);startThinkingStatusFlow(thinking);try{let res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:contextPayload(value),source:'message',lab_state:labState}),signal:currentController.signal}),data=await res.json();if(!res.ok)throw new Error(data.message||data.error||'Analyse mislukt');stopThinkingStatusFlow();render(data);removeThinking(thinking);setStatus('Analyse klaar · v'+LAB_VERSION)}catch(e){stopThinkingStatusFlow();removeThinking(thinking);try{renderFromState()}catch(_){}addAssistantMessage(analysisFallbackMessage(),[]);setStatus('Clara is klaar voor input · v'+LAB_VERSION)}finally{stopThinkingStatusFlow();clearTimeout(to);currentController=null;setAnalyzing(false);scrollBottom()}}
endPromptHost?.addEventListener('click',e=>{let b=e.target.closest('[data-agenda-end-action]');if(!b)return;handleAgendaEndPromptAction(b.dataset.itemId,b.dataset.agendaEndAction)});
chatLog.addEventListener('click',e=>{let b=e.target.closest('[data-proposal-action]');if(!b)return;if(b.dataset.proposalAction==='ok'&&b.dataset.kind==='confirm_all'){labState.agenda.forEach(i=>{if(i.status==='pencil')i.status='confirmed';i.confirmation_required=false});touchState();renderFromState()}b.closest('.options')?.remove()});
agendaSection?.addEventListener('click',e=>{let tab=e.target.closest('[data-agenda-tab]');if(tab){activeAgendaTab=tab.dataset.agendaTab;renderFromState();return}let a=e.target.closest('[data-agenda-action]');if(!a)return;let id=a.dataset.id,item=labState.agenda.find(i=>i.id===id);if(a.dataset.agendaAction==='confirm'&&item){item.status='confirmed';item.confirmation_required=false;touchState();renderFromState()}if(a.dataset.agendaAction==='delete'){labState.agenda=labState.agenda.filter(i=>i.id!==id);touchState();renderFromState()}});
agendaCol.addEventListener('pointerdown',e=>{let h=e.target.closest('[data-resize]');if(!h)return;e.preventDefault();let section=h.closest('.timeline-card'),tl=h.closest('.timeline'),item=labState.agenda.find(i=>i.id===h.dataset.id);if(!section||!tl||!item)return;dragState={id:item.id,edge:h.dataset.resize,start:Number(section.dataset.start),end:Number(section.dataset.end),rect:tl.getBoundingClientRect()};h.setPointerCapture?.(e.pointerId)});
window.addEventListener('pointermove',e=>{if(!dragState)return;let item=labState.agenda.find(i=>i.id===dragState.id);if(!item)return;let y=Math.max(0,Math.min(dragState.rect.height,e.clientY-dragState.rect.top)),min=round15(dragState.start+(y/dragState.rect.height)*(dragState.end-dragState.start)),s=timeToMin(item.start_time)||dragState.start,en=timeToMin(item.end_time)||s+30;if(dragState.edge==='start'){s=Math.min(min,en-15);item.start_time=minToTime(s)}else{en=Math.max(min,s+15);item.end_time=minToTime(en)}item.estimated_duration_minutes=Math.max(15,en-s);touchState();renderFromState()});
window.addEventListener('pointerup',()=>dragState=null);
agendaCol.addEventListener('blur',e=>{let f=e.target.dataset.agendaField,id=e.target.dataset.id;if(f==='title'&&id){let item=labState.agenda.find(i=>i.id===id);if(item){item.title=e.target.textContent.trim()||item.title;touchState();renderFromState()}}},true);
function findGuidanceSourceItem(id){return(labState.agenda||[]).find(i=>i.id===id)||(labState.tasks||[]).find(i=>i.id===id)||null}
function addLocalAgendaSuggestion(title,now){const clean=guidanceText(title,120)||'Agenda-suggestie';const m=Math.ceil(Math.max(getNowMinutes(),10*60)/15)*15;labState.agenda.push({id:'ag-local-'+Date.now(),title:clean,kind:'planned_task',date:todayIso(),start_time:now?minToTime(m):null,end_time:now?minToTime(m+30):null,estimated_duration_minutes:30,status:'pencil',confirmation_required:true,source:'guidance_rail'})}
function handleSuggestionAction(id,action,title){const item=findGuidanceSourceItem(id),clean=guidanceText(title||item?.title||id,120);if(action==='now'&&item){item.status='pencil';if(!item.start_time){const m=Math.max(getNowMinutes(),10*60);item.date=todayIso();item.start_time=minToTime(Math.ceil(m/15)*15);item.end_time=minToTime(Math.ceil(m/15)*15+(item.estimated_duration_minutes||30))}}else if(action==='now'&&!item){addLocalAgendaSuggestion(clean,true)}else if(action==='plan'&&item){item.status='pencil';item.confirmation_required=true}else if(action==='plan'&&!item){addLocalAgendaSuggestion(clean,false)}else if(action==='park'&&item){if(labState.agenda.includes(item)){item.status='needs_time';item.start_time=null;item.end_time=null}else item.done=true;labState.day_regie.rollover_candidates=[...(labState.day_regie.rollover_candidates||[]),String(item.title||'').trim()].filter(Boolean)}else if(action==='park'&&!item){labState.day_regie.rollover_candidates=[...(labState.day_regie.rollover_candidates||[]),clean].filter(Boolean)}touchState();renderFromState()}
function closeGuidanceItem(id,source){if(source==='thread'){let item=(labState.open_threads||[]).find(i=>i.id===id);if(item)item.status='closed'}else if(source==='attention'){let item=(labState.attention||[]).find(i=>i.id===id);if(item)item.done=true}else if(source==='task'){let item=(labState.tasks||[]).find(i=>i.id===id);if(item)item.done=true}else if(source==='agenda'){let item=(labState.agenda||[]).find(i=>i.id===id);if(item)item.status='needs_time'}touchState();renderFromState()}
function hangGuidanceItem(id,source){if(source==='thread'){let item=(labState.open_threads||[]).find(i=>i.id===id);if(item)item.status='hanging'}touchState();renderFromState()}
function planOpenEnd(id,source){const item=(labState.open_threads||[]).find(i=>i.id===id)||(labState.attention||[]).find(i=>i.id===id),title=item?.question||item?.title||'Open eindje plannen';if(source==='thread'&&item)item.status='hanging';addLocalAgendaSuggestion(title,false);touchState();renderFromState()}
attentionCol.addEventListener('click',e=>{let b=e.target.closest('[data-suggestion-action]');if(!b)return;handleSuggestionAction(b.dataset.id,b.dataset.suggestionAction,b.dataset.title)});
regieCol.addEventListener('click',e=>{let b=e.target.closest('[data-open-action]');if(b){if(b.dataset.openAction==='close')closeGuidanceItem(b.dataset.id,b.dataset.openSource);if(b.dataset.openAction==='hang')hangGuidanceItem(b.dataset.id,b.dataset.openSource);if(b.dataset.openAction==='plan')planOpenEnd(b.dataset.id,b.dataset.openSource);return}let clear=e.target.closest('[data-action="clear-test-state"]');if(clear){e.preventDefault();clearLocalTestState()}});
agendaPrevBtn?.addEventListener('click',()=>{activeAgendaDate=addDaysIso(activeAgendaDate||todayIso(),-1);renderFromState()});
agendaNextBtn?.addEventListener('click',()=>{activeAgendaDate=addDaysIso(activeAgendaDate||todayIso(),1);renderFromState()});
window.addEventListener('keydown',e=>{if(!e.altKey||!e.shiftKey||e.code!=='KeyR'||e.repeat)return;if(e.target&&(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA'||e.target.isContentEditable))return;e.preventDefault();clearLocalTestState()});
btn.addEventListener('click',()=>analyzeText(input.value,true));input.addEventListener('input',resizeInput);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();analyzeText(input.value,true)}});resizeInput();updateDate();setInterval(updateDate,1000);loadLabStateFromStorage();renderFromState();setInterval(checkAgendaEndPrompts,60000);(async function boot(){if(dayRegieIsEmpty(labState)&&!sessionStorage.getItem(SESSION_STARTUP_KEY)){await runAutoStartupPlanning()}else{applyStartupGreeting()}})();
