const LAB_VERSION='0.13.6';
const input=document.getElementById('input'),btn=document.getElementById('analyzeBtn'),statusEl=document.getElementById('status'),chatLog=document.getElementById('chatLog'),agendaCol=document.getElementById('agendaCol'),attentionCol=document.getElementById('attentionCol'),regieCol=document.getElementById('regieCol'),clockHour=document.getElementById('clockHour'),clockMinute=document.getElementById('clockMinute'),clockWeekday=document.getElementById('clockWeekday'),clockDate=document.getElementById('clockDate'),clockYear=document.getElementById('clockYear'),agendaPrevBtn=document.getElementById('agendaPrevBtn'),agendaNextBtn=document.getElementById('agendaNextBtn');
let labState={agenda:[],attention:[],tasks:[],day_regie:{items_to_check:[],rollover_candidates:[],review_prompt:'',suggested_time:null},updated_at:null},activeAgendaTab='day',activeAgendaDate=null,currentController=null,isAnalyzing=false,dragState=null,thinkingId=0;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function todayIso(){let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDaysIso(iso,days){let d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dateLabel(iso){let t=todayIso();if(iso===t)return'Vandaag';if(iso===addDaysIso(t,1))return'Morgen';if(iso===addDaysIso(t,2))return'Overmorgen';let d=new Date(`${iso}T12:00:00`);return d.toLocaleDateString('nl-NL',{weekday:'short',day:'numeric',month:'short'})}
function timeToMin(t){if(!t||!/^[0-2]?\d:[0-5]\d$/.test(t))return null;let[a,b]=t.split(':').map(Number);return a*60+b}
function minToTime(m){if(m>=1440)return'00:00';m=Math.max(0,m);return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function round15(m){return Math.round(m/15)*15}
function setStatus(t){if(statusEl)statusEl.textContent=t||''}
function touchState(){labState.updated_at=new Date().toISOString();setStatus('Lab State bijgewerkt · gaat mee naar Clara')}
function resizeInput(){input.style.height='32px';input.style.height=Math.min(input.scrollHeight,190)+'px'}
function scrollBottom(){chatLog.scrollTop=chatLog.scrollHeight}
function setAnalyzing(on){isAnalyzing=on;btn.classList.toggle('stop',on);btn.textContent=on?'■':'↑'}
function addUserMessage(t){chatLog.insertAdjacentHTML('beforeend',`<div class="msg user"><div class="msg-body">${esc(t)}</div></div>`);scrollBottom()}
function addThinking(){thinkingId++;let id='thinking-'+thinkingId;chatLog.insertAdjacentHTML('beforeend',`<div class="msg assistant thinking" id="${id}"><div class="msg-body"><div class="typing-indicator" aria-hidden="true"><span class="typing-dot"></span><span class="typing-dot"></span><span class="typing-dot"></span></div><div class="thinking-status" id="${id}-status" role="status" aria-live="polite"></div></div></div>`);scrollBottom();return id}
function removeThinking(id){document.getElementById(id)?.remove()}
function setThinkingStatus(thinkingId,t){let el=document.getElementById(thinkingId+'-status');if(el)el.textContent=t==null?'':String(t)}
function clearThinkingStatus(thinkingId){setThinkingStatus(thinkingId,'')}
const THINKING_STATUS_STEPS=['Input lezen','Lokale dagstaat ophalen','Projectbrain raadplegen','Projectcontext wegen','Agenda voorstel maken','Aandachtspunten scheiden','Dagregie opbouwen','Overlap controleren','Resultaat bijwerken'];
let thinkingFlowTimer=null,thinkingFlowToken=0,thinkingFlowThinkingId=null,thinkingFlowStepIdx=0;
function stopThinkingStatusFlow(){thinkingFlowToken++;if(thinkingFlowTimer){clearTimeout(thinkingFlowTimer);thinkingFlowTimer=null}thinkingFlowThinkingId=null}
function startThinkingStatusFlow(thinkingId){stopThinkingStatusFlow();thinkingFlowThinkingId=thinkingId;const my=thinkingFlowToken;thinkingFlowStepIdx=0;setThinkingStatus(thinkingId,THINKING_STATUS_STEPS[0]);function tick(){if(my!==thinkingFlowToken||thinkingFlowThinkingId!==thinkingId)return;const gap=700+Math.random()*500;thinkingFlowTimer=setTimeout(()=>{if(my!==thinkingFlowToken||thinkingFlowThinkingId!==thinkingId)return;if(thinkingFlowStepIdx<THINKING_STATUS_STEPS.length-1){thinkingFlowStepIdx++;setThinkingStatus(thinkingId,THINKING_STATUS_STEPS[thinkingFlowStepIdx]);tick()}else{function pulse(){if(my!==thinkingFlowToken||thinkingFlowThinkingId!==thinkingId)return;pulse.n=(pulse.n||0)+1;setThinkingStatus(thinkingId,pulse.n%2?THINKING_STATUS_STEPS[8]:THINKING_STATUS_STEPS[7]);thinkingFlowTimer=setTimeout(pulse,1100+Math.random()*400)}thinkingFlowTimer=setTimeout(pulse,gap)}},gap)}tick()}
function updateDate(){let n=new Date(),shown=activeAgendaDate?new Date(`${activeAgendaDate}T12:00:00`):n;clockHour.textContent=String(n.getHours()).padStart(2,'0');clockMinute.textContent=String(n.getMinutes()).padStart(2,'0');clockWeekday.textContent=shown.toLocaleDateString('en-US',{weekday:'long'});clockDate.textContent=shown.toLocaleDateString('en-GB',{day:'numeric',month:'long'}).toUpperCase();clockYear.textContent=shown.getFullYear()}
function markOverlaps(items){let out=items.map(i=>({...i,_frontend_conflict:false}));let timed=out.map((i,idx)=>({i,idx,s:timeToMin(i.start_time),e:timeToMin(i.end_time)})).filter(x=>x.s!=null);timed.forEach(x=>{if(x.e==null)x.e=x.s+(x.i.estimated_duration_minutes||30)});for(let a=0;a<timed.length;a++)for(let b=a+1;b<timed.length;b++)if(timed[a].i.date===timed[b].i.date&&timed[a].s<timed[b].e&&timed[b].s<timed[a].e){out[timed[a].idx]._frontend_conflict=true;out[timed[b].idx]._frontend_conflict=true}out.forEach(i=>{if(i.status==='conflict'&&!i._frontend_conflict)i.status='pencil'});return out}
const NEUTRAL_START=['Begin klein: één helder blok is genoeg om de dag op gang te krijgen.','Kijk eerst wat vastligt, daarna pas wat erbij kan.','Maak ruimte voor het belangrijkste, niet voor het luidste.','Vandaag hoeft niet vol; het moet kloppen.','Eerst overzicht, daarna tempo.'];
const STARTUP_SUGGESTIONS=[{label:'Maak een planning vanuit Projectbrain',prompt:'Kijk naar de lopende projecten in Projectbrain en maak daar een realistische planning van voor vandaag en morgen. Kies per project alleen de belangrijkste eerstvolgende actie, zet uitvoerbare acties in agenda of taken, zet twijfelpunten/risico\'s/keuzes in Aandacht, en geef in Dagregie aan wat ik nu het beste als eerste kan doen. Maak geen Projectbrain-dump, plan geen overlap, en zet wat niet eerlijk past apart als needs_time.'},{label:'Toon alleen wat aandacht nodig heeft',prompt:'Geef uit Projectbrain en de huidige lab state compact alleen de punten die nu echt aandacht nodig hebben per project — geen volledige dump.'},{label:'Geef per project de eerstvolgende actie',prompt:'Per project in Projectbrain: wat is de één eerstvolgende logische uitvoerbare actie? Antwoord compact, geen dump.'},{label:'Maak een richting voor deze week',prompt:'Maak vanuit Projectbrain een korte richting voor deze week (max. veertig regels): kern per project, wat eerst kan, wat bewust later blijft.'}];
const ATT_KINDS=new Set(['risico','keuze','check','wacht','past_niet','project']);
const ATT_LABEL_NL={risico:'Risico',keuze:'Keuze',check:'Check',wacht:'Wacht',past_niet:'Past niet',project:'Project'};
function simpleHash(str){let h=0;for(let i=0;i<str.length;i++)h=Math.imul(31,h)+str.charCodeAt(i)|0;return Math.abs(h)}
function rememberLastStartupGreeting(ix){try{localStorage.setItem('clara_last_greeting_ix',String(ix))}catch(_){}}
function formatAttentionLabel(kind){return ATT_LABEL_NL[kind]||'Check'}
function getAttentionType(item){return item&&ATT_KINDS.has(item.kind)?item.kind:'check'}
function coerceAttentionItem(raw,i){if(!raw)return null;if(typeof raw==='string'){const s=raw.trim();if(!s)return null;return{id:'at-'+Date.now()+'-'+i,title:s.slice(0,220),kind:'check',done:false}}const title=String(raw.title||raw.text||'').trim();if(!title)return null;const k=raw.kind&&ATT_KINDS.has(raw.kind)?raw.kind:'check';return{id:raw.id||'at-'+Date.now()+'-'+i,title:title.slice(0,220),kind:k,done:!!raw.done,project:raw.project||null}}
function normalizeAttentionItems(items){const arr=Array.isArray(items)?items:[];const out=[],seen=new Set();for(let i=0;i<arr.length;i++){const it=coerceAttentionItem(arr[i],i);if(!it)continue;const k=it.title.toLowerCase();if(seen.has(k))continue;seen.add(k);out.push(it)}return out}
function pickContextLineForStartup(ls){const agenda=markOverlaps([...(ls.agenda||[])]);if(agenda.some(i=>i._frontend_conflict))return'Er staat overlap in je agenda; los één blok eerst op.';if(agenda.some(i=>i.status==='needs_time'))return'Er staat werk zonder vaste plek; kies waar het vandaag past.';const att=normalizeAttentionItems(ls.attention||[]);const open=att.filter(i=>!i.done);if(open.length)return`Er staan ${open.length} aandachtspunten open; pak het belangrijkste eerst.`;const tk=(ls.tasks||[]).filter(t=>!t.done);if(tk.length)return`${tk.length} taken wachten; begin met de kleinste afronding.`;if(agenda.some(i=>i.status==='pencil'))return'Er staan potloodblokken klaar om te bevestigen of te schuiven.';return null}
function pickStartupGreeting(ls){const ctx=pickContextLineForStartup(ls);const pool=ctx?[ctx,...NEUTRAL_START]:NEUTRAL_START.slice();const t=new Date();const salt=`${t.getFullYear()}-${t.getMonth()+1}-${t.getDate()}-${t.getHours()}-${simpleHash(JSON.stringify({a:ls.agenda,at:ls.attention,tk:ls.tasks,dr:ls.day_regie}))}`;let h=simpleHash(salt)%pool.length;let last=-1;try{last=parseInt(localStorage.getItem('clara_last_greeting_ix')||'-1',10)}catch(_){}if(h===last)h=(h+1)%pool.length;rememberLastStartupGreeting(h);return pool[h]}
function applyStartupGreeting(){const wrap=document.querySelector('#chatLog .msg.assistant:not(.thinking)');if(!wrap)return;const text=pickStartupGreeting(labState);if(dayRegieIsEmpty(labState)){const offer='Wil je dat ik vanuit Projectbrain een realistische planning voor vandaag en morgen voorstel?';const chips=STARTUP_SUGGESTIONS.map(s=>`<button type="button" class="startup-chip" data-startup-prompt="${esc(s.prompt)}">${esc(s.label)}</button>`).join('');wrap.innerHTML=`<div class="msg-body">${esc(text)}</div><p class="startup-offer">${esc(offer)}</p><div class="startup-chips" role="group" aria-label="Voorbeeldvragen">${chips}</div>`}else{wrap.innerHTML=`<div class="msg-body">${esc(text)}</div>`}}
function ellip(s,max){s=String(s||'').trim();return s.length<=max?s:s.slice(0,max-1)+'…'}
function pickNowStep(ls){const agenda=markOverlaps([...(ls.agenda||[])]);const today=todayIso();const att=normalizeAttentionItems(ls.attention||[]);const risk=att.find(i=>!i.done&&(i.kind==='risico'||i.kind==='past_niet'));if(risk)return ellip(`${formatAttentionLabel(risk.kind)} — ${risk.title}`,72);const w=att.find(i=>!i.done&&i.kind==='wacht');if(w)return ellip(`${formatAttentionLabel(w.kind)} — ${w.title}`,72);const timed=agenda.filter(i=>(i.date||today)===today&&i.start_time&&timeToMin(i.start_time)!=null&&!classifyAllDay(i)&&i.status!=='needs_time').sort((a,b)=>(timeToMin(a.start_time)-timeToMin(b.start_time)));if(timed.length)return ellip(timed[0].title,72);const nt=agenda.find(i=>(i.date||today)===today&&i.status==='needs_time');if(nt)return ellip(`Past niet — ${nt.title}`,72);const task=(ls.tasks||[]).find(x=>!x.done);if(task)return ellip(task.title,72);const o=att.find(i=>!i.done);if(o)return ellip(`${formatAttentionLabel(o.kind)} — ${o.title}`,72);return'Kort orienteren: wat is het belangrijkste vaste punt vandaag?'}
function pickLaterChecks(ls){const d=ls.day_regie||{},lines=[];for(const t of d.items_to_check||[]){if(t&&lines.length<2)lines.push(String(t).trim())}for(const t of d.rollover_candidates||[]){if(t&&lines.length<2)lines.push(`Door: ${String(t).trim()}`)}return lines.slice(0,2).map(s=>ellip(s,76))}
function pickEndOfDayPrompt(ls){const r=String(ls.day_regie?.review_prompt||'').trim();if(r)return ellip(r,84);return'Wat blijft liggen en wat schuift bewust door?'}
function dayRegieIsEmpty(ls){const d=ls.day_regie||{};const bare=!(d.items_to_check||[]).length&&!(d.rollover_candidates||[]).length&&!String(d.review_prompt||'').trim()&&!d.suggested_time;return bare&&!(ls.agenda||[]).length&&!(ls.attention||[]).length&&!(ls.tasks||[]).length}
function buildDayRegieView(ls){if(dayRegieIsEmpty(ls))return'<div class="card regie-card"><h3>Dagregie</h3><p class="empty">Nog geen dagregie.</p><details><summary>Lab State</summary><pre>'+esc(JSON.stringify(ls,null,2))+'</pre></details></div>';const nu=pickNowStep(ls);const str=pickLaterChecks(ls);const einde=pickEndOfDayPrompt(ls);const strHtml=str.length?str.map(s=>`<div class="regie-line">${esc(s)}</div>`).join(''):'<div class="regie-line muted">—</div>';const st=ls.day_regie?.suggested_time;return`<div class="card regie-card"><h3>Dagregie</h3><div class="regie-sec"><div class="regie-h">Nu</div><div class="regie-line nu-line">${esc(ellip(nu,78))}</div></div><div class="regie-sec"><div class="regie-h">Straks</div>${strHtml}</div><div class="regie-sec"><div class="regie-h">Einde dag</div><div class="regie-line editable" contenteditable="true" data-regie-field="review_prompt">${esc(ellip(einde,84))}</div>${st?`<div class="sub">Check rond ${esc(st)}</div>`:''}</div><details><summary>Lab State</summary><pre>${esc(JSON.stringify(ls,null,2))}</pre></details></div>`}
function renderAttentionPanel(items){const norm=normalizeAttentionItems(items);if(!norm.length)return'<div class="card attention-card"><h3>Aandacht</h3><p class="empty">Geen losse aandachtspunten.</p></div>';const V=5,vis=norm.slice(0,V),more=norm.length-V;const rows=vis.map(i=>`<div class="item attention-item"><button class="box ${i.done?'done':''}" data-list-kind="attention" data-list-action="toggle" data-id="${esc(i.id)}"></button><div style="flex:1;min-width:0"><span class="att-label">${esc(formatAttentionLabel(getAttentionType(i)))}</span><div class="editable attention-title" contenteditable="true" data-list-kind="attention" data-list-field="title" data-id="${esc(i.id)}">${esc(i.title)}</div>${i.project?`<div class="sub">${esc(i.project)}</div>`:''}</div><button class="plain" data-list-kind="attention" data-list-action="delete" data-id="${esc(i.id)}">×</button></div>`).join('');const moreEl=more>0?`<div class="att-more">+ ${more} meer</div>`:'';return`<div class="card attention-card"><h3>Aandacht</h3>${rows}${moreEl}</div>`}
function classifyAllDay(i){let s=timeToMin(i.start_time),e=timeToMin(i.end_time),d=i.estimated_duration_minutes||(s!=null&&e!=null?e-s:null);return s==null||i.status==='needs_time'||d>=300}
function syncFromAnalysis(data){let agenda=markOverlaps(data.clara_agenda||[]).map((i,idx)=>({id:'ag-'+Date.now()+'-'+idx,...i}));let dash=data.dashboard_output||{};const rawAtt=[];for(const t of agenda.filter(x=>x._frontend_conflict).map(x=>x.title))if(t)rawAtt.push({title:t,kind:'risico'});for(const x of dash.attention||[]){if(typeof x==='string'&&x.trim())rawAtt.push({title:x.trim(),kind:'check'});else if(x&&x.text)rawAtt.push({title:String(x.text).trim(),kind:ATT_KINDS.has(x.kind)?x.kind:'check'})}for(const p of data.proposed_items||[])if(p.type==='attention')rawAtt.push({title:p.title,kind:'check',project:p.project||null});const attention=normalizeAttentionItems(rawAtt.map((r,i)=>({id:'at-'+Date.now()+'-'+i+'-'+((Math.random()*1e6)|0),...r,done:false})));labState={agenda,attention,tasks:(data.proposed_items||[]).filter(i=>['task','reminder'].includes(i.type)).map((i,idx)=>({id:'ta-'+Date.now()+'-'+idx,title:i.title,done:false,project:i.project||null})),day_regie:data.day_review||{items_to_check:[],rollover_candidates:[],review_prompt:'',suggested_time:null},updated_at:new Date().toISOString()}}
function renderTimeline(items,startHour,endHour,label){let start=startHour*60,end=endHour*60,total=end-start,hours=[];for(let m=start;m<=end;m+=60)hours.push(m);let labels=hours.map(m=>`<div class="hour" style="top:${(m-start)/total*100}%">${minToTime(m)}</div><div class="tick" style="top:${(m-start)/total*100}%"></div>`).join('');let lines=hours.map(m=>`<div class="line" style="top:${(m-start)/total*100}%"></div>`).join('');let blocks=items.map(i=>{let s=timeToMin(i.start_time),e=timeToMin(i.end_time),dur=i.estimated_duration_minutes||(e!=null&&s!=null?e-s:30)||30,itemEnd=e??s+dur,visibleStart=Math.max(start,s),visibleEnd=Math.min(end,itemEnd),rawH=(visibleEnd-visibleStart)/total*100,h=Math.max(3.8,rawH-1),top=(visibleStart-start)/total*100+.25,compact=(itemEnd-s)<=20||rawH<4.2,cls=i._frontend_conflict?'conflict':i.status==='confirmed'?'confirmed':'pencil',confirm=i.status==='pencil'?`<button class="plain" data-agenda-action="confirm" data-id="${esc(i.id)}">✓</button>`:'';return `<div class="event ${cls} ${compact?'compact':''}" style="top:${top}%;height:${h}%"><div class="handle top" data-resize="start" data-id="${esc(i.id)}"></div><div class="event-row"><strong class="event-title" contenteditable="true" data-agenda-field="title" data-id="${esc(i.id)}">${esc(i.title)}</strong><span class="event-time">${esc(i.start_time||'')} – ${esc(i.end_time||minToTime(itemEnd))}</span>${confirm}<button class="plain" data-agenda-action="delete" data-id="${esc(i.id)}">×</button></div><div class="handle bottom" data-resize="end" data-id="${esc(i.id)}"></div></div>`}).join('');return `<div class="timeline-card" data-start="${start}" data-end="${end}"><div class="section-head"><strong>${label}</strong><span>${minToTime(start)} – ${minToTime(end)}</span></div><div class="timeline"><div class="axis">${labels}</div><div class="events">${lines}${blocks}</div></div></div>`}
function renderAgenda(){let a=labState.agenda;if(!a.length){agendaCol.innerHTML='<p class="empty">Geen agenda-items.</p>';updateDate();return}let dates=[...new Set(a.map(i=>i.date).filter(Boolean))].sort();if(!activeAgendaDate)activeAgendaDate=dates[0]||todayIso();let dateItems=a.filter(i=>(i.date||activeAgendaDate)===activeAgendaDate);let all=dateItems.filter(classifyAllDay),timed=dateItems.filter(i=>!classifyAllDay(i)&&timeToMin(i.start_time)!=null),day=timed.filter(i=>timeToMin(i.start_time)<1140),eve=timed.filter(i=>timeToMin(i.start_time)>=1140),shown=activeAgendaTab==='day'?day:eve;updateDate();agendaCol.innerHTML=`<div class="tabs"><button class="tab ${activeAgendaTab==='day'?'active':''}" data-agenda-tab="day">Dag</button><button class="tab ${activeAgendaTab==='evening'?'active':''}" data-agenda-tab="evening">Avond</button></div><span class="pill">${all.length?all.map(i=>esc(i.title)).join(' · '):'Geen dagbrede blokken'}</span>${renderTimeline(shown,activeAgendaTab==='day'?10:19,activeAgendaTab==='day'?19:24,`${dateLabel(activeAgendaDate)} · ${activeAgendaTab==='day'?'Dag':'Avond'}`)}`}
function renderList(title,items,kind){return `<div class="card"><h3>${esc(title)}</h3>${items&&items.length?items.map(i=>`<div class="item"><button class="box ${i.done?'done':''}" data-list-kind="${kind}" data-list-action="toggle" data-id="${esc(i.id)}"></button><div style="flex:1"><div class="editable" contenteditable="true" data-list-kind="${kind}" data-list-field="title" data-id="${esc(i.id)}">${esc(i.title)}</div>${i.project?`<div class="sub">${esc(i.project)}</div>`:''}</div><button class="plain" data-list-kind="${kind}" data-list-action="delete" data-id="${esc(i.id)}">×</button></div>`).join(''):'<p class="empty">Geen.</p>'}</div>`}
function renderRegie(){regieCol.innerHTML=buildDayRegieView(labState)}
function renderFromState(){labState.agenda=markOverlaps(labState.agenda);labState.attention=normalizeAttentionItems(labState.attention);renderAgenda();attentionCol.innerHTML=renderAttentionPanel(labState.attention)+renderList('Taken',labState.tasks,'tasks');renderRegie()}
function deriveSuggestions(){let conf=labState.agenda.filter(i=>i._frontend_conflict),pencils=labState.agenda.filter(i=>i.status==='pencil');if(conf.length)return[{type:'conflict',text:'Er is overlap in je agenda. Zal ik een oplossing voorstellen?'}];if(pencils.length)return[{type:'confirm_all',text:'Klopt deze planning zo? Dan bevestig ik alle potloodblokken.'}];return[]}
function addAssistantMessage(text,suggestions){let opt=suggestions&&suggestions.length?`<div class="options"><div class="option-text">${esc(suggestions[0].text)}</div><div class="option-actions"><button data-proposal-action="decline">Afslaan</button><button data-proposal-action="ok" data-kind="${esc(suggestions[0].type)}">Okay</button></div></div>`:'';chatLog.insertAdjacentHTML('beforeend',`<div class="msg assistant"><div class="msg-body">${esc(text)}</div>${opt}</div>`);scrollBottom()}
function contextPayload(message){return 'Actuele lokale Clara Lab State, inclusief handmatige wijzigingen. Behandel dit als waarheid:\n'+JSON.stringify(labState,null,2)+'\n\nNieuw bericht:\n'+message}
function render(data){syncFromAnalysis(data);renderFromState();addAssistantMessage(String(data.summary||'Ik heb je planning rechts in de agenda gezet.').slice(0,520),deriveSuggestions())}
async function analyzeText(message,showUser=true){if(isAnalyzing&&currentController){currentController.abort();return}let value=String(message||'').trim();if(!value){setStatus('Voer eerst tekst in.');return}if(showUser)addUserMessage(value);input.value='';resizeInput();currentController=new AbortController();setAnalyzing(true);setStatus('Clara analyseert met lokale Lab State...');let thinking=addThinking(),to=setTimeout(()=>currentController.abort(),60000);startThinkingStatusFlow(thinking);try{let res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:contextPayload(value),source:'message',lab_state:labState}),signal:currentController.signal}),data=await res.json();if(!res.ok)throw new Error(data.message||data.error||'Analyse mislukt');stopThinkingStatusFlow();removeThinking(thinking);render(data);setStatus('Analyse klaar · v'+LAB_VERSION)}catch(e){stopThinkingStatusFlow();setThinkingStatus(thinking,e.name==='AbortError'?'Gestopt':'Analyse mislukt');await new Promise(r=>setTimeout(r,680));removeThinking(thinking);setStatus(e.name==='AbortError'?'Analyse gestopt.':e.message)}finally{stopThinkingStatusFlow();clearTimeout(to);currentController=null;setAnalyzing(false);scrollBottom()}}
chatLog.addEventListener('click',e=>{const chip=e.target.closest('[data-startup-prompt]');if(chip){const p=chip.getAttribute('data-startup-prompt')||'';if(p){input.value=p;resizeInput();input.focus();setStatus('Klaar om te versturen — druk op ↑ of Enter.');return}}let b=e.target.closest('[data-proposal-action]');if(!b)return;if(b.dataset.proposalAction==='ok'&&b.dataset.kind==='confirm_all'){labState.agenda.forEach(i=>{if(i.status==='pencil')i.status='confirmed';i.confirmation_required=false});touchState();renderFromState()}b.closest('.options')?.remove()});
agendaCol.addEventListener('click',e=>{let tab=e.target.closest('[data-agenda-tab]');if(tab){activeAgendaTab=tab.dataset.agendaTab;renderFromState();return}let a=e.target.closest('[data-agenda-action]');if(!a)return;let id=a.dataset.id,item=labState.agenda.find(i=>i.id===id);if(a.dataset.agendaAction==='confirm'&&item){item.status='confirmed';item.confirmation_required=false;touchState();renderFromState()}if(a.dataset.agendaAction==='delete'){labState.agenda=labState.agenda.filter(i=>i.id!==id);touchState();renderFromState()}});
agendaCol.addEventListener('pointerdown',e=>{let h=e.target.closest('[data-resize]');if(!h)return;e.preventDefault();let section=h.closest('.timeline-card'),tl=h.closest('.timeline'),item=labState.agenda.find(i=>i.id===h.dataset.id);if(!section||!tl||!item)return;dragState={id:item.id,edge:h.dataset.resize,start:Number(section.dataset.start),end:Number(section.dataset.end),rect:tl.getBoundingClientRect()};h.setPointerCapture?.(e.pointerId)});
window.addEventListener('pointermove',e=>{if(!dragState)return;let item=labState.agenda.find(i=>i.id===dragState.id);if(!item)return;let y=Math.max(0,Math.min(dragState.rect.height,e.clientY-dragState.rect.top)),min=round15(dragState.start+(y/dragState.rect.height)*(dragState.end-dragState.start)),s=timeToMin(item.start_time)||dragState.start,en=timeToMin(item.end_time)||s+30;if(dragState.edge==='start'){s=Math.min(min,en-15);item.start_time=minToTime(s)}else{en=Math.max(min,s+15);item.end_time=minToTime(en)}item.estimated_duration_minutes=Math.max(15,en-s);touchState();renderFromState()});
window.addEventListener('pointerup',()=>dragState=null);
agendaCol.addEventListener('blur',e=>{let f=e.target.dataset.agendaField,id=e.target.dataset.id;if(f==='title'&&id){let item=labState.agenda.find(i=>i.id===id);if(item){item.title=e.target.textContent.trim()||item.title;touchState();renderFromState()}}},true);
function handleListAction(e){let a=e.target.closest('[data-list-action]');if(!a)return;let arr=a.dataset.listKind==='attention'?labState.attention:a.dataset.listKind==='tasks'?labState.tasks:null;if(!arr)return;if(a.dataset.listAction==='toggle'){let item=arr.find(i=>i.id===a.dataset.id);if(item)item.done=!item.done}if(a.dataset.listAction==='delete')arr.splice(arr.findIndex(i=>i.id===a.dataset.id),1);touchState();renderFromState()}
attentionCol.addEventListener('click',handleListAction);
function handleListBlur(e){let k=e.target.dataset.listKind,f=e.target.dataset.listField,id=e.target.dataset.id,arr=k==='attention'?labState.attention:k==='tasks'?labState.tasks:null;if(f==='title'&&id&&arr){let item=arr.find(i=>i.id===id);if(item){item.title=e.target.textContent.trim()||item.title;touchState();renderFromState()}}if(e.target.dataset.regieField==='review_prompt'){labState.day_regie.review_prompt=e.target.textContent.trim();touchState();renderFromState()}}
attentionCol.addEventListener('blur',handleListBlur,true);regieCol.addEventListener('blur',handleListBlur,true);
agendaPrevBtn?.addEventListener('click',()=>{activeAgendaDate=addDaysIso(activeAgendaDate||todayIso(),-1);renderFromState()});
agendaNextBtn?.addEventListener('click',()=>{activeAgendaDate=addDaysIso(activeAgendaDate||todayIso(),1);renderFromState()});
btn.addEventListener('click',()=>analyzeText(input.value,true));input.addEventListener('input',resizeInput);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();analyzeText(input.value,true)}});resizeInput();updateDate();setInterval(updateDate,1000);renderFromState();applyStartupGreeting();
